### ISSUE TITLE
add internationalization package

### ISSUE THREAD

**Issue by georgettica** [moniquelive/gocheat#1]
as seen in https://github.com/moniquelive/gocheat/blob/main/query_screen.go#L41, the strings are not english.
this can be solved using https://github.com/nicksnyder/go-i18n

let me know if you are planning to do this or I should submit a PR

**Comment by moniquelive** [comment]
@georgettica very good idea! I’ll give it a shot. I’ve never worked with i18n in go. Thanks!

**Comment by georgettica** [comment]
Neither have I, but I guess it's a good place to start from :)

**Comment by moniquelive** [comment]
I used a much simpler (but much harder to use) go/text package: 8fded5c05dc3922aee292b58dbba18f230e88d1a

**Comment by georgettica** [comment]
Nice!
Learned something new

Thanks!
